### PR TITLE
Fix for 'No Server is assigned' bug

### PR DESCRIPTION
**Pull request by kamranjon**
Found the fix here: https://github.com/neo4j-contrib/neo4j-elasticsearch/issues/33

All I did was apply the suggested fix, and it worked for me.

### CODE REVIEW

**Comment by jexp** [comment]
The problem is that it removes 'JestDefaultHttpConfigFactory' which is important for the ssl use-case.

Can you add your fix rather there?

**Comment by kamranjon** [comment]
Ok, I updated what seemed to be the common changes, the readTimeout and put it into the JestConfig but now the bug is back - maybe it has something to do with this line in there? 
`.discoveryFrequency(1L, TimeUnit.MINUTES)`

**Comment by kamranjon** [comment]
Can confirm that the issue was with the discoveryEnabled(true) option being set - cannot debug further as I don't have enough context on what those options are used for in conjunction with the project.

**Comment by jexp** [comment]
So we could make that an option that's configurable via neo4j.conf config.
something like:

elasticsearch.discovery=true/false

Do you think you could look into that and send a PR ?

**Pull request closed without merging**
